#!/bin/sh

# add all the jars anywhere in the lib/ directory to our classpath
here=$(dirname $0)
CLASSES=$here/bin
CLASSES=$CLASSES:$(echo $here/lib/*.jar | tr ' ' :)
CLASSES=$CLASSES:$here/geoSGLM.jar

java -XX:ParallelGCThreads=2 -Xmx8000m -ea -classpath $CLASSES $*
